services:
  - type: web
    name: amazon-scraper-api
    runtime: python

    envVars:
      - key: PLAYWRIGHT_BROWSERS_PATH
        value: 0

    buildCommand: |
      pip install -r requirements.txt
      python -m playwright install chromium

    startCommand: gunicorn app:app